version: '2'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  api:
    build: git@github.com/DockerCon2017/api.git
    ports:
      - "3000:3000"
    links:
      - "db"
    environment:
      - MONGODB_HOST: db
  web:
    build: .
    ports:
      - "80:80"
    links:
      - "api"
    environment:
      - API_HOST: api
